<?xml version="1.0"?>
<robot name="vehicle_v1" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="base_l" value="0.15" />
    <xacro:property name="base_w" value="0.12" />
    <xacro:property name="base_h" value="0.05" />

    <xacro:property name="wh_l" value="0.033" />
    <xacro:property name="wh_r" value="0.033" />
    <xacro:property name="wh_base_l" value="0.162" />
    <xacro:property name="wh_base_w" value="0.15" />
    <xacro:property name="wh_base_z" value="0.00" />

    <link name="base_link">
        <!-- pose and inertial -->
        <pose>0 0 0 0 0 0</pose>
        <inertial>
            <mass value="2" />
            <origin rpy="0 0 0" xyz="0 0 ${-base_h/2}" />
            <inertia ixx="0.206208333333" ixy="0" ixz="0" iyy="0.206208333333" iyz="0" izz="0.206208333333" />
        </inertial>
        <!--   -->
        <!-- <collision name="collision_chassis">
            <origin rpy="0 0 0" xyz="0 0 ${-base_h/2}" />
            <geometry>
                <box size="${base_l/2} ${base_w/2} ${base_h/2}" />
            </geometry>
        </collision> -->
        <visual>
            <origin rpy="0 0 0" xyz="0 0 ${-base_h/2}" />
            <geometry>
                <box size="${base_l} ${base_w} ${base_h}" />
            </geometry>
            <material name="blue" />
        </visual>
    </link>

    <joint name="camera_joint" type="fixed">
        <axis xyz="0 1 0" />
        <origin xyz="0.121 0.0 0.2" rpy="0 0.5 0" />
        <parent link="base_link" />
        <child link="camera1_link" />
    </joint>

    <!-- Camera -->
    <link name="camera1_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.04 0.04 0.04" />
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.04 0.04 0.04" />
            </geometry>
            <material name="gray" />
        </visual>

        <inertial>
            <mass value="1e-5" />
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
        </inertial>
    </link>


    <xacro:macro name="wheel" params="name xyz">
        <joint name="${name}_cont_joint" type="continuous">
            <origin rpy="0 0 0" xyz="0 0 0" />
            <child link="${name}_wheel_link" />
            <parent link="${name}_j_link" />
            <axis rpy="0 0 0" xyz="0 1 0" />
            <!-- <limit effort="10000" velocity="2" /> -->
            <joint_properties damping="0.0" friction="0.0" />
            <dynamics damping="0.0" friction="0.0"/>
        </joint>
        <joint name="${name}_rev_joint" type="revolute">
            <origin rpy="0 0 0" xyz="${xyz}" />
            <child link="${name}_j_link" />
            <parent link="base_link" />
            <axis rpy="0 0 0" xyz="0 0 1" />
            <limit effort="10000" velocity="1" lower="-1.57" upper="1.57" />
            <!-- <joint_properties damping="10000" friction="0"/> -->
            <!-- <joint_properties damping="0" friction="0" /> -->
            <dynamics damping="0.0" friction="0.0"/>
        </joint>
        <link name="${name}_wheel_link">
            <inertial>
                <mass value="0.1" />
                <origin rpy="0 1.5707 1.5707" xyz="0 0 0" />
                <inertia ixx="0.000526666666667" ixy="0" ixz="0" iyy="0.000526666666667" iyz="0" izz="0.001" />
            </inertial>
            <collision>
                <origin rpy="0 1.5707 1.5707" xyz="0 0 0" />
                <geometry>
                    <cylinder length="${wh_l}" radius="${wh_r}" />
                </geometry>
            </collision>
            <visual>
                <origin rpy="0 1.5707 1.5707" xyz="0 0 0" />
                <geometry>
                    <cylinder length="${wh_l}" radius="${wh_r}" />
                </geometry>
            </visual>
        </link>
        <link name="${name}_j_link">
            <inertial>
                <mass value="0.1" />
                <origin xyz="0 0 0" rpy="0 0 0" />
                <inertia ixx="1e-3" ixy="0" ixz="0" iyy="1e-3" iyz="0" izz="1e-3" />
            </inertial>
        </link>
        <transmission name="${name}_rev_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${name}_rev_joint">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${name}_rev_motor">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

        <transmission name="${name}_cont_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${name}_cont_joint">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${name}_cont_motor">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>
    <xacro:macro name="wheel_b" params="name xyz">
        <joint name="${name}_cont_joint" type="continuous">
            <origin rpy="0 0 0" xyz="0 0 0" />
            <child link="${name}_wheel_link" />
            <parent link="${name}_j_link" />
            <axis rpy="0 0 0" xyz="0 1 0" />
            <joint_properties damping="0.0" friction="0.0" />
            <!-- <limit effort="10000" velocity="2" /> -->
            <!-- <joint_properties damping="10000" friction="0" /> -->
            <!-- <joint_properties damping="0" friction="0" /> -->
            <dynamics damping="0.0" friction="0.0"/>
        </joint>
        <joint name="${name}_f_joint" type="fixed">
            <origin rpy="0 0 0" xyz="${xyz}" />
            <child link="${name}_j_link" />
            <parent link="base_link" />
            <axis rpy="0 0 0" xyz="0 0 1" />
                <!-- <limit effort="10000" velocity="1" lower="-1.57" upper="1.57" /> -->
            <!-- <joint_properties damping="10000" friction="0"/> -->
            <!-- <joint_properties damping="0" friction="0" /> -->
            <dynamics damping="0.0" friction="0.0"/>
        </joint>
        <link name="${name}_wheel_link">
            <inertial>
                <mass value="0.1" />
                <origin rpy="0 1.5707 1.5707" xyz="0 0 0" />
                <inertia ixx="0.000526666666667" ixy="0" ixz="0" iyy="0.000526666666667" iyz="0" izz="0.001" />
            </inertial>
            <collision>
                <origin rpy="0 1.5707 1.5707" xyz="0 0 0" />
                <geometry>
                    <cylinder length="${wh_l}" radius="${wh_r}" />
                </geometry>
            </collision>
            <visual>
                <origin rpy="0 1.5707 1.5707" xyz="0 0 0" />
                <geometry>
                    <cylinder length="${wh_l}" radius="${wh_r}" />
                </geometry>
            </visual>
        </link>
        <link name="${name}_j_link">
            <inertial>
                <mass value="1e-5" />
                <origin xyz="0 0 0" rpy="0 0 0" />
                <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
            </inertial>
        </link>
        <!--
        <transmission name="${name}_rev_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${name}_rev_joint">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${name}_rev_motor">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

        <transmission name="${name}_cont_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${name}_cont_joint">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${name}_cont_motor">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            </transmission>
        -->
    </xacro:macro>


    <xacro:wheel_b name="back_left" xyz="${-wh_base_l/2} ${wh_base_w/2} ${wh_base_z}" />
    <xacro:wheel_b name="back_right" xyz="${-wh_base_l/2} ${-wh_base_w/2} ${wh_base_z}" />
    <xacro:wheel name="front_left" xyz="${wh_base_l/2} ${wh_base_w/2} ${wh_base_z}" />
    <xacro:wheel name="front_right" xyz="${wh_base_l/2} ${-wh_base_w/2} ${wh_base_z}" />


    <gazebo reference="camera1_link">
        <sensor type="camera" name="camera1">
            <update_rate>30.0</update_rate>
            <camera name="head">
                <horizontal_fov>1.5</horizontal_fov>
                <image>
                    <width>1280</width>
                    <height>720</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.02</near>
                    <far>300</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <!-- Noise is sampled independently per pixel on each frame.
               That pixel's noise value is added to each of its color
               channels, which at that point lie in the range [0,1]. -->
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                </noise>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>0.0</updateRate>
                <cameraName>camera1</cameraName>
                <imageTopicName>image_raw</imageTopicName>
                <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                <frameName>/camera1_link</frameName>
                <hackBaseline>0.07</hackBaseline>
                <distortionK1>0.0</distortionK1>
                <distortionK2>0.0</distortionK2>
                <distortionK3>0.0</distortionK3>
                <distortionT1>0.0</distortionT1>
                <distortionT2>0.0</distortionT2>
            </plugin>
        </sensor>
    </gazebo>
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/vehicle_v1</robotNamespace>
        </plugin>
    </gazebo>

</robot>
