<?xml version="1.0"?>
<robot name="vehicle_v1" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="base_l" value="0.3" />
    <xacro:property name="base_w" value="0.15" />
    <xacro:property name="base_h" value="0.05" />

    <xacro:property name="wh_l" value="0.03" />

    <xacro:property name="wh_base_l" value="0.34" />
    <xacro:property name="wh_base_w" value="0.1" />
    <xacro:property name="wh_base_z" value="-0.05" />

    <link name="base_link">
        <!-- pose and inertial -->
        <pose>0 0 0 0 0 0</pose>
        <inertial>
            <mass value="0.5" />
            <origin rpy="0 0 0" xyz="0 0 ${-base_h/2}" />
            <inertia ixx="0.206208333333" ixy="0" ixz="0" iyy="0.206208333333" iyz="0" izz="0.206208333333" />
        </inertial>
        <!--   -->
        <!-- <collision name="collision_chassis">
            <origin rpy="0 0 0" xyz="0 0 ${-base_h/2}" />
            <geometry>
                <box size="${base_w} ${base_l} ${base_h}" />
            </geometry>
        </collision> -->
        <visual>
            <origin rpy="0 0 0" xyz="0 0 ${-base_h/2}" />
            <geometry>
                <box size="${base_w} ${base_l} ${base_h}" />
            </geometry>
            <material name="blue" />
        </visual>
    </link>

    <joint name="camera_joint" type="fixed">
        <axis xyz="0 1 0" />
        <origin xyz="0 0.1 0.2" rpy="0 0.5 0" />
        <parent link="base_link" />
        <child link="camera1_link" />
    </joint>

    <!-- Camera -->
    <link name="camera1_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.04 0.04 0.04" />
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.04 0.04 0.04" />
            </geometry>
            <material name="red" />
        </visual>

        <inertial>
            <mass value="1e-5" />
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
        </inertial>
    </link>

    <gazebo reference="camera1_link">
        <sensor type="camera" name="camera1">
            <update_rate>30.0</update_rate>
            <camera name="head">
                <horizontal_fov>1.2262634</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image> 
                <clip>
                    <near>0.02</near>
                    <far>300</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <!-- Noise is sampled independently per pixel on each frame.
               That pixel's noise value is added to each of its color
               channels, which at that point lie in the range [0,1]. -->
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                </noise>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>0.0</updateRate>
                <cameraName>camera1</cameraName>
                <imageTopicName>image_raw</imageTopicName>
                <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                <frameName>/camera1_link</frameName>
                <hackBaseline>0.07</hackBaseline>
                <distortionK1>0.0</distortionK1>
                <distortionK2>0.0</distortionK2>
                <distortionK3>0.0</distortionK3>
                <distortionT1>0.0</distortionT1>
                <distortionT2>0.0</distortionT2>
            </plugin>
        </sensor>
    </gazebo>


</robot>
